### ISSUE TITLE
[ask] {reactive: false} vs pulich-cache

### ISSUE THREAD

**Issue by osv** [yubozhao/meteor-publish-cache#4]
Hello, does this package actual? Perfomance vs `reactive: false`

>* If you call `observe` or `observeChanges` on a cursor created with `Collection.find(query, {reactive: false})`, it now only calls initial add callbacks and does not continue watching the query.

**Comment by osv** [comment]
Ah, sorry, `reactive: false` is client only, server still use mergebox.

**Comment by yubozhao** [comment]
@osv  no worries.  The purpose of this package is send down information you dont update too often, so it doesn't take up subscription space(which requires constant server side resource).

**Comment by osv** [comment]
Yes, but for my project better meteor method + null collection, because named collection may be filled by vanilla subscribe. Pulich-cache can be used too, but there no way to clean  data that I don't need automaticly, so null collection :)
